apiVersion: v1
kind: Namespace
metadata:
  name: llm-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-frontend-app
  namespace: llm-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-frontend
  template:
    metadata:
      labels:
        app: llm-frontend
    spec:
      containers:
        - name: llm-frontend
          image: sritampatnaik/llm-frontend-python:1.0.0
          ports:
            - containerPort: 5000
          env:
            - name: BACKEND_URL
              value: http://llm-multiroute-service.llm-multiroute-backend.svc.cluster.local:8080
---
apiVersion: v1
kind: Service
metadata:
  name: llm-frontend-service
  namespace: llm-frontend
spec:
  selector:
    app: llm-frontend
  ports:
    - port: 5000
      targetPort: 5000
